common_args:
  training_type: "simulation"
  random_seed: 0

#  [Dataset + Model] :
#  mnist  lr / cnn
#  femnist  cnn
#  cifar10  cnn_web
#  svhn  cnn

data_args:
  dataset: "mnist"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn"

train_args:
  federated_optimizer: "HierarchicalFL"
  client_id_list: "[]"
  client_num_in_total: 20
  client_num_per_round: 20
  comm_round: 100
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  # group_method: "random"
  group_method: "custom"
  custom_group_str: "{0: [0, 1, 2, 3], 1: [4, 5, 6, 7], 2: [8, 9, 10, 11], 3: [12, 13, 14, 15], 4: [16, 17, 18, 19]}" # GACE will override this
  group_num: 5
  group_comm_round: 5
  lr: 0.001
  reputations: []
  low_quality_ratio: 0.0  # Ratio of low-quality clients (0.0, 0.1, 0.2, 0.3, 0.4, 0.5)

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: gace_torch_hierachicalfl_mnist
  using_mlops: false

